apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: catalog-service
  description: |
    Catalog Application for ICD10, Coverages ...

    [![ArgoCD Status](https://v2202402203466256255.megasrv.de/argocd/api/badge?name=catalog-application&revision=false)](https://v2202402203466256255.megasrv.de/argocd/applications/catalog-application)
    
    [![Quality Gate Status](https://sonarcloud.io/api/project_badges/measure?project=org.goafabric%3Acatalog-batch-service-quarkus&metric=alert_status&token=12796876fefc746ce4df3f11130bbfd6abf9d752)](https://sonarcloud.io/summary/new_code?id=org.goafabric%3Acatalog-batch-service-quarkus)
    [![Coverage](https://sonarcloud.io/api/project_badges/measure?project=org.goafabric%3Acatalog-batch-service-quarkus&metric=coverage&token=12796876fefc746ce4df3f11130bbfd6abf9d752)](https://sonarcloud.io/summary/new_code?id=org.goafabric%3Acatalog-batch-service-quarkus)
    
    [![Security Rating](https://sonarcloud.io/api/project_badges/measure?project=org.goafabric%3Acatalog-batch-service-quarkus&metric=security_rating&token=12796876fefc746ce4df3f11130bbfd6abf9d752)](https://sonarcloud.io/summary/new_code?id=org.goafabric%3Acatalog-batch-service-quarkus)
    [![Reliability Rating](https://sonarcloud.io/api/project_badges/measure?project=org.goafabric%3Acatalog-batch-service-quarkus&metric=reliability_rating&token=12796876fefc746ce4df3f11130bbfd6abf9d752)](https://sonarcloud.io/summary/new_code?id=org.goafabric%3Acatalog-batch-service-quarkus)
    [![Maintainability Rating](https://sonarcloud.io/api/project_badges/measure?project=org.goafabric%3Acatalog-batch-service-quarkus&metric=sqale_rating&token=12796876fefc746ce4df3f11130bbfd6abf9d752)](https://sonarcloud.io/summary/new_code?id=org.goafabric%3Acatalog-batch-service-quarkus)
  tags:
    - spring-boot
    - batch
  annotations:
    github.com/project-slug: goafabric/catalog-batch-service-quarkus
    github.com/actions: goafabric/catalog-batch-service-quarkus
    argocd/app-name: catalog-application
    backstage.io/adr-location: https://github.com/goafabric/backstage/tree/develop/catalog/adr/catalog-service/
    kiali.io/provider: default
    kiali.io/namespace: core
  links:
    - url: https://github.com/goafabric/catalog-service
      title: GitHub Repository
    - url: https://v2202402203466256255.megasrv.de/catalog/
      title: Service URL

spec:
  type: service
  lifecycle: production
  owner: team-blue
  providesApis:
    - catalog-api
  dependsOn:
    - resource:catalog-db
  dependencyOf:
    - component:api-gateway

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: catalog-api
  description: OpenAPI definition for Core Service.
  tags:
    - openapi
    - catalog-service
spec:
  type: openapi
  lifecycle: production
  owner: team-blue
  definition:
    $text: doc/generated/openapi.json

---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: catalog-db
  annotations:
    backstage.io/database: "postgres"
    postgres.instance: "my-postgres-cluster"
    postgres.database: "catalog"
spec:
  type: database
  owner: devops

